### ISSUE TITLE
Differences with original repo?

### ISSUE THREAD

**Issue by alecive** [baxter-flowers/track_ik#1]
Hello @ymollard , 

I am wondering what is the difference between your trac_ik fork and the original repository. I have seen that you implemented a `setEpsilon` method, but my question was mainly related to this line https://github.com/baxter-flowers/trac_ik/commit/633c4e6b6f201b02921cc10212b8dd6d9da012a9#diff-497da70f9b8e2d05d867cc917df84bc8R101

Why you decided to add a `reset` there? What are the advantages of doing that?

**Comment by ymollard** [comment]
Hi @alecive,

This `reset` is intended to be called after `setEpsilon`. If you don't reset NLOPT_IK and the KDL IK Solver, the new epsilon is not taken into account.

We wanted to allow the TRAC IK solver to return approximative solutions when the goal is not precisely reachable, but it looks like it confuses people more than it helps, and we finally got a much better result be solving [IK by optimization](https://github.com/baxter-flowers/promplib/blob/master/src/promp/ik.py#L7-L44).

**Comment by alecive** [comment]
Good to know! My experience with IK has been always optimization-based (we use it on the iCub robot), but now that I moved to the Baxter and ROS I didn't find anything comparable, and I really don't have time to work on that. Thanks for the link, I'll have a look at that!
